services:
  - type: web
    name: inventory-manager
    runtime: static
    buildCommand: npm install; npm run build
    staticPublishPath: ./dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VITE_API_URL
        fromService:
          name: inventory-manager-api
          type: web
          property: host