/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppSuppliersRouteImport } from './routes/_app/suppliers'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppProfileRouteImport } from './routes/_app/profile'
import { Route as AppEquiposRouteImport } from './routes/_app/equipos'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppChatbotRouteImport } from './routes/_app/chatbot'
import { Route as AppMovementsIndexRouteImport } from './routes/_app/movements/index'
import { Route as AppCatalogoIndexRouteImport } from './routes/_app/catalogo/index'
import { Route as AppMovementsIdRouteImport } from './routes/_app/movements/$id'
import { Route as AppCatalogoIdRouteImport } from './routes/_app/catalogo/$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSuppliersRoute = AppSuppliersRouteImport.update({
  id: '/suppliers',
  path: '/suppliers',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppEquiposRoute = AppEquiposRouteImport.update({
  id: '/equipos',
  path: '/equipos',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppChatbotRoute = AppChatbotRouteImport.update({
  id: '/chatbot',
  path: '/chatbot',
  getParentRoute: () => AppRoute,
} as any)
const AppMovementsIndexRoute = AppMovementsIndexRouteImport.update({
  id: '/movements/',
  path: '/movements/',
  getParentRoute: () => AppRoute,
} as any)
const AppCatalogoIndexRoute = AppCatalogoIndexRouteImport.update({
  id: '/catalogo/',
  path: '/catalogo/',
  getParentRoute: () => AppRoute,
} as any)
const AppMovementsIdRoute = AppMovementsIdRouteImport.update({
  id: '/movements/$id',
  path: '/movements/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppCatalogoIdRoute = AppCatalogoIdRouteImport.update({
  id: '/catalogo/$id',
  path: '/catalogo/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/chatbot': typeof AppChatbotRoute
  '/dashboard': typeof AppDashboardRoute
  '/equipos': typeof AppEquiposRoute
  '/profile': typeof AppProfileRoute
  '/settings': typeof AppSettingsRoute
  '/suppliers': typeof AppSuppliersRoute
  '/catalogo/$id': typeof AppCatalogoIdRoute
  '/movements/$id': typeof AppMovementsIdRoute
  '/catalogo': typeof AppCatalogoIndexRoute
  '/movements': typeof AppMovementsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/chatbot': typeof AppChatbotRoute
  '/dashboard': typeof AppDashboardRoute
  '/equipos': typeof AppEquiposRoute
  '/profile': typeof AppProfileRoute
  '/settings': typeof AppSettingsRoute
  '/suppliers': typeof AppSuppliersRoute
  '/catalogo/$id': typeof AppCatalogoIdRoute
  '/movements/$id': typeof AppMovementsIdRoute
  '/catalogo': typeof AppCatalogoIndexRoute
  '/movements': typeof AppMovementsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/chatbot': typeof AppChatbotRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/equipos': typeof AppEquiposRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/suppliers': typeof AppSuppliersRoute
  '/_app/catalogo/$id': typeof AppCatalogoIdRoute
  '/_app/movements/$id': typeof AppMovementsIdRoute
  '/_app/catalogo/': typeof AppCatalogoIndexRoute
  '/_app/movements/': typeof AppMovementsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/chatbot'
    | '/dashboard'
    | '/equipos'
    | '/profile'
    | '/settings'
    | '/suppliers'
    | '/catalogo/$id'
    | '/movements/$id'
    | '/catalogo'
    | '/movements'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/chatbot'
    | '/dashboard'
    | '/equipos'
    | '/profile'
    | '/settings'
    | '/suppliers'
    | '/catalogo/$id'
    | '/movements/$id'
    | '/catalogo'
    | '/movements'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/_app/chatbot'
    | '/_app/dashboard'
    | '/_app/equipos'
    | '/_app/profile'
    | '/_app/settings'
    | '/_app/suppliers'
    | '/_app/catalogo/$id'
    | '/_app/movements/$id'
    | '/_app/catalogo/'
    | '/_app/movements/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/suppliers': {
      id: '/_app/suppliers'
      path: '/suppliers'
      fullPath: '/suppliers'
      preLoaderRoute: typeof AppSuppliersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/equipos': {
      id: '/_app/equipos'
      path: '/equipos'
      fullPath: '/equipos'
      preLoaderRoute: typeof AppEquiposRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/chatbot': {
      id: '/_app/chatbot'
      path: '/chatbot'
      fullPath: '/chatbot'
      preLoaderRoute: typeof AppChatbotRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/movements/': {
      id: '/_app/movements/'
      path: '/movements'
      fullPath: '/movements'
      preLoaderRoute: typeof AppMovementsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/catalogo/': {
      id: '/_app/catalogo/'
      path: '/catalogo'
      fullPath: '/catalogo'
      preLoaderRoute: typeof AppCatalogoIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/movements/$id': {
      id: '/_app/movements/$id'
      path: '/movements/$id'
      fullPath: '/movements/$id'
      preLoaderRoute: typeof AppMovementsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/catalogo/$id': {
      id: '/_app/catalogo/$id'
      path: '/catalogo/$id'
      fullPath: '/catalogo/$id'
      preLoaderRoute: typeof AppCatalogoIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppChatbotRoute: typeof AppChatbotRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppEquiposRoute: typeof AppEquiposRoute
  AppProfileRoute: typeof AppProfileRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppSuppliersRoute: typeof AppSuppliersRoute
  AppCatalogoIdRoute: typeof AppCatalogoIdRoute
  AppMovementsIdRoute: typeof AppMovementsIdRoute
  AppCatalogoIndexRoute: typeof AppCatalogoIndexRoute
  AppMovementsIndexRoute: typeof AppMovementsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppChatbotRoute: AppChatbotRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppEquiposRoute: AppEquiposRoute,
  AppProfileRoute: AppProfileRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppSuppliersRoute: AppSuppliersRoute,
  AppCatalogoIdRoute: AppCatalogoIdRoute,
  AppMovementsIdRoute: AppMovementsIdRoute,
  AppCatalogoIndexRoute: AppCatalogoIndexRoute,
  AppMovementsIndexRoute: AppMovementsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
